tasks:
  - name: tf_task
    before: |
      cd $PROJECT_ROOT
      source ./bin/install_terraform_cli
      source ./bin/generate_tfrc_credential
      cp $GITPOD_REPO_ROOT/terraform.tfvars.example $GITPOD_REPO_ROOT/terraform.tfvars
      source ./bin/set_tf_alias
  - name: aws_task
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd $PROJECT_ROOT   
      source ./bin/install_aws_cli
      source ./bin/build_provider
  - name: http-server
    before: |
      cd $PROJECT_ROOT
      npm install --global http-server
    command: 
      http-server      
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform