tasks:
  - name: tf_task
    before: |
      cd $GITPOD_REPO_ROOT
      pwd
      source ./bin/install_terraform_cli
      source ./bin/generate_tfrc_credential
      cp $GITPOD_REPO_ROOT/terraform.tfvars.example $GITPOD_REPO_ROOT/terraform.tfvars
  - name: aws_task
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd $GITPOD_REPO_ROOT    
      source ./bin/install_aws_cli
      gp sync-done aws_task
  - name: workspace
    before: |
      source ./bin/set_tf_alias
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform